CREATE OR REPLACE TRIGGER TR1_REGION
BEFORE INSERT OR UPDATE OR DELETE
ON REGIONS
FOR EACH ROW--SE EJECUTA POR CADA REGISTRO DE LA TABLA
WHEN (NEW.REGION_ID>1000) --LA CLAUSULA WHEN SE USA PARA EJECUTAR EL TRIGGER CUANDO SE CUMPLE UNA CONDICION
BEGIN
    IF INSERTING THEN 
        --SE CONVIERTE A MAYUSCULAS EL NOMBRE DE LA REGION
        :NEW.REGION_NAME:=UPPER(:NEW.REGION_NAME);--:NEW SE USA PARA REFERENCIAR EL NUEVO VALOR DE UNA COLUMNA
        INSERT INTO LOG_TABLES VALUES('INSERCION',USER);
    END IF;
    IF UPDATING ('REGION_NAME') THEN 
        --SE CONVIERTE A MAYUSCULAS EL NOMBRE DE LA REGION
        :NEW.REGION_NAME:=UPPER(:NEW.REGION_NAME);
        INSERT INTO LOG_TABLES VALUES('UPDATE REGION_NAME',USER);
    END IF;
    IF UPDATING ('REGION_ID') THEN 
        INSERT INTO LOG_TABLES VALUES('UPDATE REGION_ID',USER);
    END IF;
        IF DELETING THEN 
            INSERT INTO LOG_TABLES VALUES('DELETE',USER);
    END IF;

    /*IF USER <> 'HR' THEN
        RAISE_APPLICATION_ERROR(-20001,'SOLO HR PUEDE TRABAJAR EN REGIONS');
    END IF;*/
END;