CREATE OR REPLACE PACKAGE PKG1
IS 
    PROCEDURE CONVERT(NAME VARCHAR2, CONVESION_TYPE CHAR);
END;
/

CREATE OR REPLACE PACKAGE BODY PKG1
IS 
    FUNCTION UPPER_NAME(NAME VARCHAR2)
    RETURN VARCHAR2
    IS
    BEGIN
        RETURN UPPER(NAME);
    END UPPER_NAME;
    

    FUNCTION LOWER_NAME(NAME VARCHAR2)
    RETURN VARCHAR2
    IS
    BEGIN
        RETURN LOWER(NAME);
    END LOWER_NAME;

    PROCEDURE CONVERT(NAME VARCHAR2, CONVESION_TYPE CHAR)
    IS
    BEGIN
        IF CONVESION_TYPE = 'U' THEN
            DBMS_OUTPUT.PUT_LINE(UPPER_NAME(NAME));
        ELSIF CONVESION_TYPE = 'L' THEN
            DBMS_OUTPUT.PUT_LINE(LOWER_NAME(NAME));
        ELSE
            DBMS_OUTPUT.PUT_LINE('CONVERSION NO VALIDA');
        END IF;
    END CONVERT;
END PKG1;