CREATE OR REPLACE TRIGGER INS_EMPL --SE CREA UN TRIGGER LLAMADO INS_EMPL
AFTER INSERT ON REGIONS --SE EJECUTA DESPUES DE INSERTAR UN REGISTRO EN LA TABLA REGIONS
BEGIN
    --SE INSERTA UN REGISTRO EN LA TABLA LOG_TABLES ademas se inserta el usuario que inserto el registro.
    INSERT INTO LOG_TABLES VALUES('INSERCION EN LA TABLA REGIONS',USER);
END;