--EXCEPTIONS: SIRVEN PARA MANEJAR ERRORES, SON 2 TIPOS: PREDEFINIDAS Y NO PREDEFINIDAS:
--PREDEFINIDAS: SON LAS QUE ORACLE YA TIENE DEFINIDAS, POR EJEMPLO LA NO_DATA_FOUND
--NO PREDEFINIDAS: SON LAS QUE NOSOTROS DEFINIMOS, POR EJEMPLO SI QUEREMOS QUE SE MUESTRE UN MENSAJE CUANDO NO SE ENCUENTRA UN REGISTRO
DECLARE
    EMPL EMPLOYEES%ROWTYPE;
BEGIN
    SELECT * INTO EMPL
    FROM EMPLOYEES
    WHERE EMPLOYEE_ID = 100;
    dbms_output.put_line(EMPL.FIRST_NAME);    
END;