--Procedure CALC_TAX_OUT
CREATE OR REPLACE PROCEDURE CALC_TAX_IN_OUT
(EMPL IN EMPLOYEES.EMPLOYEE_ID%TYPE, 
    T1 IN OUT NUMBER)
IS
    SAL NUMBER:=0;
BEGIN
    IF T1 < 0 OR T1 > 60 THEN
        RAISE_APPLICATION_ERROR(-20001,'EL Porcentaje debe estar entre 0 y 60');
    END IF;
    SELECT SALARY INTO SAL FROM EMPLOYEES WHERE EMPLOYEE_ID=EMPL;
        DBMS_OUTPUT.PUT_LINE('T=' || T1);
        T1:=SAL*T1/100;
        DBMS_OUTPUT.PUT_LINE('Salario: ' || SAL);
    EXCEPTION
    WHEN NO_DATA_FOUND THEN
        DBMS_OUTPUT.PUT_LINE('No se encontro el empleado');
END;
