--SELECTS MULTIPLES CON ARRAYS ASOCIATIVOS: SE USA PARA ALMACENAR LOS DATOS DE UNA TABLA EN UN ARRAY
--LOS SELECTS MULTIPLES: SE USAN PARA ALMACENAR LOS DATOS DE UNA TABLA EN UN ARRAY
--LOS ARRAYS ASOCIATIVOS: SON ARRAYS QUE SE ASOCIAN CON UN INDICE NUMERICO
SET SERVEROUTPUT ON
DECLARE
    TYPE DEPARTAMENTOS IS TABLE OF
        DEPARTMENTS%ROWTYPE
    INDEX BY PLS_INTEGER;

    DEPTS DEPARTAMENTOS;

    BEGIN
        --Se aplican 2 for loops para recorrer el array de departamentos, se asigna a DEPTS el departamento con ID 10,20,30,40,50,60,70,80,90,100   
        FOR I IN 1..10 LOOP 
            SELECT * INTO DEPTS(I) FROM DEPARTMENTS WHERE DEPARTMENT_ID=I*10;
            --DBMS_OUTPUT.PUT_LINE(DEPTS(I).DEPARTMENT_ID || ': ' || DEPTS(I).DEPARTMENT_NAME);    
        END LOOP;

        --Este for loop recorre el array de departamentos, desde el primer elemento hasta el ultimo
        FOR I IN DEPTS.FIRST..DEPTS.LAST LOOP
        --NUMERO Y NOMBRE DEL DEPARTAMENTO CONCATENADOS
        DBMS_OUTPUT.PUT_LINE(DEPTS(I).DEPARTMENT_ID || ': ' || DEPTS(I).DEPARTMENT_NAME);    
        END LOOP;
END;