SET SERVEROUTPUT ON 
DECLARE
    -- ARRAYS ASOCIATIVOS: SON ARRAYS QUE SE ASOCIAN CON UN INDICE NUMERICO
    TYPE DEPARTAMENTOS IS TABLE OF -- SE DEFINE UN TIPO DE DATO DEPARTAMENTOS QUE ES UN ARRAY
        DEPARTMENTS.DEPARTMENT_NAME%TYPE
    INDEX BY PLS_INTEGER; -- AQUI SE ASOCIA EL INDICE CON UN NUMERO ENTERO

    TYPE EMPLEADOS IS TABLE OF 
        EMPLOYEES%ROWTYPE
    INDEX BY PLS_INTEGER; 

    -- DEPTS Y EMPS SON VARIABLES DE TIPO DEPARTAMENTOS Y EMPLEADOS
    DEPTS DEPARTAMENTOS;
    EMPS EMPLEADOS;

BEGIN
    -- TIPO SIMPLE: SE ASIGNA UN VALOR A LA VARIABLE DEPTS
    DEPTS(1) := 'IT';
    DEPTS(2) := 'HR';
    DEPTS(55):='PRUEBA';
    -- SE ASIGNA UN VALOR A LA VARIABLE DEPTS
    DBMS_OUTPUT.PUT_LINE(DEPTS(1));
    DBMS_OUTPUT.PUT_LINE(DEPTS(2));

    -- DESPUES DE ASIGNAR LOS VALORES, SE PUEDE SABER CUANTOS ELEMENTOS TIENE EL ARRAY
    DBMS_OUTPUT.PUT_LINE(DEPTS.LAST); -- LAST: DEVUELVE EL ULTIMO ELEMENTO DEL ARRAY
    DBMS_OUTPUT.PUT_LINE(DEPTS.FIRST); -- FIRST: DEVUELVE EL PRIMER ELEMENTO DEL ARRAY

    -- SE PUEDE SABER SI UN ELEMENTO EXISTE EN EL ARRAY
    IF DEPTS.EXISTS(3) THEN -- CORREGIDO: EXISTS en lugar de EXIST
        DBMS_OUTPUT.PUT_LINE('EXISTE');
    ELSE
        DBMS_OUTPUT.PUT_LINE('NO EXISTE');
    END IF;

    -- TIPO COMPUESTO
    SELECT * INTO EMPS(1) FROM EMPLOYEES WHERE EMPLOYEE_ID = 100;
    DBMS_OUTPUT.PUT_LINE(EMPS(1).FIRST_NAME);
END;