--FUNCION CON PAQUETE
CREATE OR REPLACE PACKAGE PKG1
IS 
    FUNCTION CONVERT (NAME VARCHAR2, CONVERSION_TYPE CHAR) RETURN VARCHAR2;
END;
/

CREATE OR REPLACE PACKAGE BODY PKG1
IS 
    FUNCTION UPPER_NAME(NAME VARCHAR2)
    RETURN VARCHAR2
IS  
BEGIN
    RETURN UPPER(NAME);
END UPPER_NAME;

FUNCTION LOWER_NAME(NAME VARCHAR2)
    RETURN VARCHAR2
    IS 
    BEGIN
        RETURN LOWER(NAME);
    END LOWER_NAME;

FUNCTION CONVERT (NAME VARCHAR2, CONVERSION_TYPE CHAR)
    RETURN VARCHAR2
    IS
    BEGIN
        IF CONVERSION_TYPE = 'U' THEN
            RETURN UPPER_NAME(NAME);
        ELSIF CONVERSION_TYPE = 'L' THEN
            RETURN LOWER_NAME(NAME);
        ELSE
            RETURN 'EL PARAMETRO DEBE SER U O L';
        END IF;
    END CONVERT;
END PKG1;